name: golf-scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Test
        run: pytest -q
      - name: Run scraper
        run: python main.py --out out/events.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: events-json
          path: out/events.json
